#!/usr/bin/env python3
"""Stamp one version + date across every place csdid records them.

The version lived in ~13 hand-maintained places and had already drifted: the
five .ado headers and five .sthlp headers carried two different dates
(07jul2026 and 09jul2026) for the same release. Hand-editing that many sites is
how a package ships claiming to be a version it is not.

Usage
    tools/release/stamp-version.py --check
    tools/release/stamp-version.py --version 2.1.0 [--date 26jul2026]

--check exits non-zero if the sites disagree, and is wired into
tests/meta/test-version-consistency.sh.

Sites covered:
  src/ado/*.ado          `*! <name> <ver> ... <date>` header
  src/ado/csdid.ado      the `csdid version` display string and every
                         `ereturn local version`
  src/ado/csdid_stats.ado  `ereturn local version`
  src/help/*.sthlp       `{* *! version <ver> <date>}` header
  csdid.pkg              `d Distribution-Date: YYYYMMDD`
Files under build/ and pkg/ are generated by src/build.do and are not edited
here; rebuild after stamping.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ADOS = sorted((ROOT / "src" / "ado").glob("*.ado"))
HELPS = sorted((ROOT / "src" / "help").glob("*.sthlp"))
PKG = ROOT / "csdid.pkg"

ADO_HDR = re.compile(r"^(\*! \S+ )(\S+)( )(\d{2}\w{3}\d{4})", re.M)
HELP_HDR = re.compile(r"^(\{\* \*! version )(\S+)( )(\d{2}\w{3}\d{4})(\})", re.M)
ERETURN_V = re.compile(r'(ereturn local version ")([^"]+)(")')
DISPLAY_V = re.compile(r'(display as text "csdid version )([^"]+)(")')
DIST_DATE = re.compile(r"^(d Distribution-Date: )(\d{8})", re.M)


def collect() -> dict[str, set[str]]:
    """version strings and date strings actually present, by kind."""
    vers: set[str] = set()
    dates: set[str] = set()
    for p in ADOS:
        t = p.read_text()
        for m in ADO_HDR.finditer(t):
            vers.add(m.group(2)); dates.add(m.group(4))
        for m in ERETURN_V.finditer(t):
            vers.add(m.group(2))
        for m in DISPLAY_V.finditer(t):
            vers.add(m.group(2))
    for p in HELPS:
        for m in HELP_HDR.finditer(p.read_text()):
            vers.add(m.group(2)); dates.add(m.group(4))
    return {"versions": vers, "dates": dates}


def check() -> int:
    found = collect()
    status = 0
    if len(found["versions"]) != 1:
        print(f"version strings disagree: {sorted(found['versions'])}", file=sys.stderr)
        status = 1
    if len(found["dates"]) != 1:
        print(f"date stamps disagree: {sorted(found['dates'])}", file=sys.stderr)
        status = 1
    if PKG.exists() and not DIST_DATE.search(PKG.read_text()):
        print("csdid.pkg has no 'd Distribution-Date:' line", file=sys.stderr)
        status = 1
    if status == 0:
        v = next(iter(found["versions"])); d = next(iter(found["dates"]))
        print(f"version consistent: {v} ({d})")
    return status


def stamp(version: str, date: str) -> None:
    iso = _dt.datetime.strptime(date, "%d%b%Y").strftime("%Y%m%d")
    for p in ADOS:
        t = p.read_text()
        t = ADO_HDR.sub(lambda m: m.group(1) + version + m.group(3) + date, t)
        t = ERETURN_V.sub(lambda m: m.group(1) + version + m.group(3), t)
        t = DISPLAY_V.sub(lambda m: m.group(1) + version + m.group(3), t)
        p.write_text(t)
    for p in HELPS:
        t = HELP_HDR.sub(
            lambda m: m.group(1) + version + m.group(3) + date + m.group(5), p.read_text()
        )
        p.write_text(t)
    if PKG.exists():
        PKG.write_text(DIST_DATE.sub(lambda m: m.group(1) + iso, PKG.read_text()))
    print(f"stamped {version} ({date}, Distribution-Date {iso})")
    print("now rebuild:  stata-mp -b do src/build.do   (regenerates build/ and pkg/)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--version")
    ap.add_argument("--date", help="Stata-style, e.g. 26jul2026; defaults to today")
    a = ap.parse_args()
    if a.check or not a.version:
        return check()
    date = a.date or _dt.date.today().strftime("%d%b%Y").lower()
    stamp(a.version, date)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
