#!/usr/bin/env python3
"""Stamp one version + date across every place csdid records them.

The version lives in ~13 places. Left hand-maintained they drift -- the five
.ado headers and the five .sthlp headers can carry two different dates for the
same release -- and hand-editing that many sites is how a package ships
claiming to be a version it is not.

Usage
    tools/release/stamp-version.py --check
    tools/release/stamp-version.py --version 2.1.0 [--date 26jul2026]

--check exits non-zero if the sites disagree, and is wired into
tests/meta/test-version-consistency.sh.

Sites covered:
  src/ado/*.ado          `*! <name> <ver> ... <date>` header
  src/mata/csdid.mata    the same header. It ships, and on Stata 14/15/16 it
                         is the file that actually executes, so it is not a
                         file that can be left without one.
  src/ado/csdid.ado      the `csdid version` display string and every
                         `ereturn local version`
  src/ado/csdid_stats.ado  `ereturn local version`
  src/help/*.sthlp       `{* *! version <ver> <date>}` header
  csdid.pkg              `d Distribution-Date: YYYYMMDD` (value compared to
                         the stamped date, not just present) and `d Version:`
  src/legacy/*.ado       the same `*!` header as src/ado
  the compiled library's stamp, which is a version string in four files:
                         src/mata/csdid.mata      "<ver>|source"
                         src/ado/_csdid_engine_load.ado
                                                  what the loader accepts
                         src/build.do             what it compiles in, and the
                                                  assertion that it did
                         tests/stata/test-mlib-session.do  the staged arms
                         A stamp that does not move with the package is worse
                         than no stamp: a 2.0.0 library left behind by an
                         earlier install becomes indistinguishable from the
                         2.1.0 one, which is the exact failure the stamp was
                         added to prevent. The one version literal that must
                         NOT move -- another csdid's, in the test's
                         `other_pkg' macro -- is held in a macro so that it is
                         not written in a shape this file would rewrite.
Files under build/ and pkg/ are generated by src/build.do and are not edited
here; rebuild after stamping.
"""
from __future__ import annotations

import argparse
import datetime as _dt
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
ADOS = sorted((ROOT / "src" / "ado").glob("*.ado")) + sorted(
    (ROOT / "src" / "legacy").glob("*.ado")
)
MATAS = sorted((ROOT / "src" / "mata").glob("*.mata"))
HELPS = sorted((ROOT / "src" / "help").glob("*.sthlp"))
PKG = ROOT / "csdid.pkg"

ADO_HDR = re.compile(r"^(\*! \S+ )(\S+)( )(\d{2}\w{3}\d{4})", re.M)
HELP_HDR = re.compile(r"^(\{\* \*! version )(\S+)( )(\d{2}\w{3}\d{4})(\})", re.M)
ERETURN_V = re.compile(r'(ereturn local version ")([^"]+)(")')
DISPLAY_V = re.compile(r'(display as text "csdid version )([^"]+)(")')
DIST_DATE = re.compile(r"^(d Distribution-Date: )(\d{8})", re.M)
PKG_VERSION = re.compile(r"^(d Version: )(\S+)", re.M)

# The compiled library's stamp. Every one of these is the package half of
# `<version>|<who built it>`; each pattern captures (prefix, version, suffix).
MLIB_STAMP = {
    "source": re.compile(r'(")([0-9][^"|]*)(\|source")'),
    "built": re.compile(r'(")([0-9][^"|]*)(\|`c\(stata_version\)\'")'),
    "newer": re.compile(r'(")([0-9][^"|]*)(\|`newer_stata\'")'),
    "accepted": re.compile(r'("`mlib_pkg\'" != ")([^"]+)(")'),
}
# What each file must still show. A pattern that stops matching means the
# stamp was rewritten in a shape this script no longer recognises, which
# leaves it free to drift again -- so a missing site is a failure, and it has
# to be missing PER FILE: the same pattern matching somewhere else is not
# evidence that this file still carries its stamp.
MLIB_FILES = {
    ROOT / "src" / "mata" / "csdid.mata": ("source",),
    ROOT / "src" / "ado" / "_csdid_engine_load.ado": ("accepted",),
    ROOT / "src" / "build.do": ("source", "built"),
    ROOT / "tests" / "stata" / "test-mlib-session.do": ("source", "built", "newer"),
}


def collect() -> dict[str, set[str]]:
    """version strings and date strings actually present, by kind."""
    vers: set[str] = set()
    dates: set[str] = set()
    for p in ADOS + MATAS:
        t = p.read_text()
        for m in ADO_HDR.finditer(t):
            vers.add(m.group(2)); dates.add(m.group(4))
        for m in ERETURN_V.finditer(t):
            vers.add(m.group(2))
        for m in DISPLAY_V.finditer(t):
            vers.add(m.group(2))
    for p in HELPS:
        for m in HELP_HDR.finditer(p.read_text()):
            vers.add(m.group(2)); dates.add(m.group(4))
    for p in MLIB_FILES:
        t = p.read_text()
        for rx in MLIB_STAMP.values():
            for m in rx.finditer(t):
                vers.add(m.group(2))
    return {"versions": vers, "dates": dates}


def mlib_stamp_sites() -> dict[str, int]:
    """How many library-stamp sites each file still shows, by pattern name."""
    counts: dict[str, int] = {}
    for p, required in MLIB_FILES.items():
        t = p.read_text()
        for name in required:
            counts[f"{p.relative_to(ROOT)}:{name}"] = len(MLIB_STAMP[name].findall(t))
    return counts


def check() -> int:
    found = collect()
    status = 0
    if len(found["versions"]) != 1:
        print(f"version strings disagree: {sorted(found['versions'])}", file=sys.stderr)
        status = 1
    for site, n in mlib_stamp_sites().items():
        if n == 0:
            print(f"the library stamp is gone from {site}", file=sys.stderr)
            status = 1
    if len(found["dates"]) != 1:
        print(f"date stamps disagree: {sorted(found['dates'])}", file=sys.stderr)
        status = 1
    if PKG.exists():
        pkg_text = PKG.read_text()
        dd = DIST_DATE.search(pkg_text)
        pv = PKG_VERSION.search(pkg_text)
        if not dd:
            print("csdid.pkg has no 'd Distribution-Date:' line", file=sys.stderr)
            status = 1
        elif len(found["dates"]) == 1:
            # The VALUE is compared, not just the line's existence: the two
            # release-date authorities (the *! stamps and the .pkg) once
            # disagreed for 22 days with this check green.
            want = _dt.datetime.strptime(
                next(iter(found["dates"])), "%d%b%Y"
            ).strftime("%Y%m%d")
            if dd.group(2) != want:
                print(
                    f"csdid.pkg Distribution-Date {dd.group(2)} disagrees with "
                    f"the stamped date {next(iter(found['dates']))} (= {want})",
                    file=sys.stderr,
                )
                status = 1
        if not pv:
            print("csdid.pkg has no 'd Version:' line", file=sys.stderr)
            status = 1
        elif len(found["versions"]) == 1 and pv.group(2) != next(iter(found["versions"])):
            print(
                f"csdid.pkg 'd Version: {pv.group(2)}' disagrees with the stamped "
                f"version {next(iter(found['versions']))}",
                file=sys.stderr,
            )
            status = 1
    if status == 0:
        v = next(iter(found["versions"])); d = next(iter(found["dates"]))
        print(f"version consistent: {v} ({d})")
    return status


def stamp(version: str, date: str) -> None:
    iso = _dt.datetime.strptime(date, "%d%b%Y").strftime("%Y%m%d")
    for p in ADOS + MATAS:
        t = p.read_text()
        t = ADO_HDR.sub(lambda m: m.group(1) + version + m.group(3) + date, t)
        t = ERETURN_V.sub(lambda m: m.group(1) + version + m.group(3), t)
        t = DISPLAY_V.sub(lambda m: m.group(1) + version + m.group(3), t)
        p.write_text(t)
    for p in HELPS:
        t = HELP_HDR.sub(
            lambda m: m.group(1) + version + m.group(3) + date + m.group(5), p.read_text()
        )
        p.write_text(t)
    if PKG.exists():
        pkg_text = PKG.read_text()
        pkg_text = DIST_DATE.sub(lambda m: m.group(1) + iso, pkg_text)
        pkg_text = PKG_VERSION.sub(lambda m: m.group(1) + version, pkg_text)
        PKG.write_text(pkg_text)
    for p in MLIB_FILES:
        t = p.read_text()
        for rx in MLIB_STAMP.values():
            t = rx.sub(lambda m: m.group(1) + version + m.group(3), t)
        p.write_text(t)
    print(f"stamped {version} ({date}, Distribution-Date {iso})")
    print("now rebuild:  stata-mp -b do src/build.do   (regenerates build/ and pkg/)")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--version")
    ap.add_argument("--date", help="Stata-style, e.g. 26jul2026; defaults to today")
    a = ap.parse_args()
    if a.check or not a.version:
        return check()
    date = a.date or _dt.date.today().strftime("%d%b%Y").lower()
    stamp(a.version, date)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
