#!/usr/bin/env bash
set -euo pipefail

# The bias and coverage figures published in the comparison article must agree
# with the committed Monte Carlo summary.
#
# The published speed numbers are generated from a committed results file and
# gated. The bias and coverage numbers are not generated by anything the tree
# runs: they are transcribed from a Monte Carlo that takes hours, so between
# one run and the next the estimation engine can change underneath them and
# every gate stays green. Re-running the simulation is the only way to learn
# whether they still hold, and nothing makes that comparison unless this does.
#
# The checker refuses rather than reporting agreement when it matches too few
# cells, because a comparison that covers a minority of the table is not a
# verification of the table.

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

SUMMARY="tools/bench/field/results/reliability-summary.txt"
if [ ! -f "$SUMMARY" ]; then
  echo "missing $SUMMARY -- re-run simmc.do and commit its summary" >&2
  exit 1
fi

exec python3 tools/release/check-reliability-tables.py "$SUMMARY"
