#!/usr/bin/env bash
set -euo pipefail

doc="docs/legacy-migration-guide.md"
test -f "$doc"

grep -qF 'R `did` 2.5.1' "$doc"
grep -qF 'the default `bal(full)` drops the units not observed in every' "$doc"
grep -qF 'available only on request as `bal(pair)`' "$doc"
grep -qF '`method(dripw)`' "$doc"
grep -qF '`method(stdipw)`' "$doc"
grep -qF '`asinr`' "$doc"
grep -qF '`wboot(wtype(rademacher))`' "$doc"
grep -qF '`wboot(wbtype(mammen))`' "$doc"
grep -qF '`wboot reps(#) seed(#)`, `wboot reps(#) rseed(#)`' "$doc"
grep -qF '`id(idvar)`' "$doc"
grep -qF '`notyettreated`, `nevertreated`' "$doc"
grep -qF '`vce(cluster clustvar)`' "$doc"
grep -qF '`csdid_stats event`, `csdid_stats, type(event)`' "$doc"
grep -qF '`estat dynamic`, `estat simple`, `estat group`, `estat calendar`' "$doc"
grep -qF '`bal(full)`, `balance(full)`, `bal(unbal)`' "$doc"
grep -qF '`long`, `long2`' "$doc"
grep -qF 'Use the test suite under `tests/` as the migration map' "$doc"
grep -qF 'documented divergences' "$doc"
grep -qF 'None of them restores legacy per-comparison unit dropping' "$doc"
