"""Emit the Stata block that compares e(attgt) against an R oracle.

Used by the behavioral -> measured conversions: each inherited test gains a
block that captures every ATT(g,t) cell it produces, merges against the R
fixture generated by tools/parity/generators/<id>/generate.R, and asserts
agreement. Keeping it here rather than retyping it per test means the
comparison logic is identical everywhere and fixable in one place.

Usage from a conversion script:

    import sys; sys.path.insert(0, "tools/parity")
    from oracle_block import block
    open(test_path, "a").write(block("py012", 54, calls, "(label)"))
"""
def block(fid, n, calls, label, note=None):
    """Emit the Stata comparison block appended to an inherited test."""
    note = note or ("The assertions above check structure and loose bounds; they never compared a\n"
                    "* value against R. This pins every cell of the scenarios below.")
    return f"""
* ---------------------------------------------------------------------------
* {fid.upper()} R-oracle comparison (added 2026-07-27)
* {note}
* ---------------------------------------------------------------------------
confirm file "`root'/tests/fixtures/parity/{fid}/expected/r/attgt.csv"
tempfile {fid}_actual
quietly {{
    clear
    set obs 0
    gen str60 scenario = ""
    gen double group = .
    gen double time = .
    gen double att_stata = .
    gen double se_stata = .
    save "`{fid}_actual'", replace emptyok
}}
capture program drop {fid}_grab
program define {fid}_grab
    args tag store
    tempname A
    matrix `A' = e(attgt)
    local nr = rowsof(`A')
    preserve
    quietly {{
        clear
        set obs `nr'
        gen str60 scenario = "`tag'"
        gen double group = .
        gen double time = .
        gen double att_stata = .
        gen double se_stata = .
        forvalues i = 1/`nr' {{
            replace group     = `A'[`i',1] in `i'
            replace time      = `A'[`i',2] in `i'
            replace att_stata = `A'[`i',4] in `i'
            replace se_stata  = `A'[`i',5] in `i'
        }}
        append using "`store'"
        save "`store'", replace
    }}
    restore
end
{calls}
import delimited using "`root'/tests/fixtures/parity/{fid}/expected/r/attgt.csv", clear asdouble varnames(1)
quietly merge 1:1 scenario group time using "`{fid}_actual'", assert(match) nogen
quietly count
assert r(N) == {n}
quietly generate double d_att = abs(att - att_stata)
quietly generate double d_se  = abs(se - se_stata)
quietly summarize d_att, meanonly
assert r(max) < 1e-9
quietly summarize d_se, meanonly
assert r(max) < 1e-9
display "{fid.upper()} OK: {n} cells {label} match R to <1e-9"
"""
